# Generated by Django 2.2.24 on 2021-12-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
