# Generated by Django 2.2.24 on 2021-12-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0005_auto_20211226_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hood',
            new_name='NeighbourHood',
        ),
    ]
