# Generated by Django 2.2.24 on 2021-12-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0014_auto_20211228_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
