# Generated by Django 2.2.24 on 2021-12-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0015_business_business_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='owner',
        ),
    ]
