# Generated by Django 2.2.24 on 2021-12-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0017_auto_20211228_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='owner',
        ),
    ]
