# Generated by Django 2.2.24 on 2021-12-28 21:09

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0018_auto_20211228_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='health_tell',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='police_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
