# Generated by Django 2.2.24 on 2021-12-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0019_auto_20211229_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
    ]
