# Generated by Django 2.2.24 on 2021-12-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0020_auto_20211229_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_photo',
            field=models.ImageField(default='v1639327874/images/default_drurzc.jpg', upload_to='images/'),
        ),
    ]
