# Generated by Django 2.2.24 on 2021-12-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0021_auto_20211229_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
