# Generated by Django 2.2.24 on 2021-12-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0022_auto_20211229_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='administrator',
            new_name='area_administrator',
        ),
    ]
